name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run unit and integration tests
        run: |
          ./run_tests.sh || true
          python -m pytest -q

      - name: Upload test summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            test_reports/
            results/
            simulacion_*.log
          if-no-files-found: ignore

      - name: Fail if pytest failed
        if: ${{ failure() }}
        run: exit 1
